import Dictionary from '../../../public/icon/dictionary.svg'
import Course from '../../../public/icon/course.svg'
import Topic from '../../../public/icon/topic.svg'
import Exam from '../../../public/icon/exam.svg'
import Apple from '../../../public/icon/apple.svg'
import Android from '../../../public/icon/android.svg'
import Facebook from '../../../public/icon/facebook.svg'
import Twitter from '../../../public/icon/twitter.svg'
import Linkedin from '../../../public/icon/linkedin.svg'
import Instagram from '../../../public/icon/instagram.svg'
import Star from '../../../public/icon/star.svg'
import LargePerson from '../../../public/icon/large-person.svg'
import LargeWoman from '../../../public/icon/woman.svg'
import Success from '../../../public/icon/success.svg'
import Dropdown from '../../../public/icon/dropdown.svg'
import Avatar from '../../../public/icon/avatar.svg'
import Search from '../../../public/icon/search.svg'
import AvatarThinking from '../../../public/icon/avatar-thinking.svg'
import LoudSpeaker from '../../../public/icon/loudspeaker.svg'
import CryIcon from '../../../public/icon/cry.svg'
import NoCourse1 from '../../../public/icon/no-course1.svg'
import NoCourse2 from '../../../public/icon/no-course2.svg'
import Viewer from '../../../public/icon/view.svg'
import NoImageWord from '../../../public/icon/no-image-word.svg'
import BookHeart from '../../../public/icon/book-heart.svg'
import Game1 from '../../../public/icon/game-1.svg'
import Game2 from '../../../public/icon/game-2.svg'
import Game3 from '../../../public/icon/game-3.svg'
import Game4 from '../../../public/icon/game-4.svg'
import Game5 from '../../../public/icon/game-5.svg'
import Game6 from '../../../public/icon/game-6.svg'
import Question from '../../../public/icon/question.svg'
import CorrectAnswer from '../../../public/icon/correct-anwser.svg'
import WrongAnswer from '../../../public/icon/wrong-anwser.svg'
import NextBlueArrow from '../../../public/icon/next-blue-arrow.svg'
import UserHeart from '../../../public/icon/user-heart.svg'
import UserSquare from '../../../public/icon/user-square.svg'
import SaveIcon from '../../../public/icon/save.svg'
import AvatarGirl from '../../../public/icon/avatar-girl.svg'
import Education1 from '../../../public/icon/education-1.svg'
import Education2 from '../../../public/icon/education-2.svg'
import Education3 from '../../../public/icon/education-3.svg'
import Education4 from '../../../public/icon/education-4.svg'
export {
    Avatar, Dictionary, Course, Topic, Exam, Android,
    Apple, Facebook, Twitter, Linkedin, Instagram, Star, LargePerson,
    LargeWoman, Success, Dropdown, Search, AvatarThinking, LoudSpeaker, CryIcon,
    NoCourse1, NoCourse2, Viewer, NoImageWord, BookHeart, Game1, Game2, Game3,
    Question, WrongAnswer, CorrectAnswer, Game4, Game5, Game6, NextBlueArrow,
    UserHeart, UserSquare, SaveIcon, AvatarGirl, Education1, Education2, Education3, Education4
}